### ISSUE TITLE
remove limitation of flist mountpoint

### ISSUE THREAD

**Issue by maxux** [Jumpscale/aysfs#17]
When flist point to "/opt/something", it should not _need_ to point to /opt in mount destination.

**Comment by muhamadazmy** [comment]
Fixed by commit cb7da5a199dc328043b1f6d9cf19a8abe754ba2f

Now you can mount your plist under any location, Considering the plist paths to be relative.

For example:
If your plist has the following lines

```
/path/to/file.1
/path/to/file.2
```

And then you mounted this under /mnt/test/
The absolute file path will be
```
/mnt/test/path/to/file.1
/mnt/test/path/to/file.2
```
